name: Sample Orca Image Scan Workflow
on:
  # Trigger the workflow on push request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  orca-iac_scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Run Orca Container Image Scan
      id: orcasecurity
      uses: orcasecurity/shiftleft-container-image-action@v1
      with:
        api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
        project_key: default
        image: redis:latest
        format: "sarif"
    - name: Get the output from the gitleaks step
      if: always()
      run: |
        echo "exitcode: ${{ steps.orcasecurity.outputs.exitcode }}"
        echo "result: ${{ steps.orcasecurity.outputs.result }}"
        echo "command: ${{ steps.orcasecurity.outputs.command }}"
        echo "report: ${{ steps.orcasecurity.outputs.report }}"
        echo "output: ${ORCA_OUTPUT}"
      env:
        ORCA_OUTPUT: ${{ steps.orcasecurity.outputs.output }}

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: orcaresults/image.sarif
