name: Sample Orca Image Scan Workflow
on:
  # Trigger the workflow on push request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  orca-iac_scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Run Orca Container Image Scan
      id: orca-container-image-scan
      uses: orcasecurity/shiftleft-container-image-action@v1
      with:
        api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
        project_key: default
        image: asfascascascasc:latest
        format: "sarif"
        output:
          "results/"

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      if: ${{ steps.orca-container-image-scan.outputs.exitcode == 1 }}
      with:
        sarif_file: results/image.sarif
